### PR TITLE
updated nuget package CommonServiceLocator to 1.3.0

### PR DESCRIPTION
**Pull request by dhindrik**

### CODE REVIEW

**Comment by tillig** [comment]
What was the reason for this change? Were you unable to just update your local project and use binding redirects to allow the local change?

**Comment by dhindrik** [comment]
I couldn't get it working in Xamarin Studio with redirect, if I used Visual Studio it worked.

**Comment by tillig** [comment]
We try to avoid changing dependencies if we can to ensure maximum backward compatibility. Can you ask someone who knows about Xamarin Studio to help troubleshoot with you (or ask a question on StackOverflow)? It would be good to see that there's no other way to solve this before we make a change.

**Comment by tillig** [comment]
[This bug on the Xamarin Studio Bugzilla](https://bugzilla.xamarin.com/show_bug.cgi?id=22670) seems similar and may offer some ideas.

**Pull request closed without merging**
